# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(rhino)
library(bslib)
library(htmltools)
library(leaflet)
library(glue)
library(shinyWidgets)
library(base)
library(DT)
library(naijR)
library(purrr)
library(dplyr)
library(tibble)
library(shinyauthr)
library(purrr)
library(shinyjs)
library(bsicons)
library(shiny.router)

# options(renv.download.override = utils::download.file)
