# app/logic/sitesData.R

box::use(
  base[structure]
)

sites_data <- function() {
  structure(list(
    continent = c(
      "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa",
      "Africa", "Africa", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America", "Asia", "Australia", "Europe", "North America",
      "South America"
    ), country = c(
      "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria",
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA
    ), state = c(
      "Enugu", "Enugu", "Imo", "Imo", "Imo", "Imo",
      "Imo", "Imo", "Imo", "Imo", "Imo", "Imo", "Imo", "Imo", "Imo",
      "Enugu", "Imo", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia",
      "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia",
      "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia",
      "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia",
      "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Abia", "Enugu",
      "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Enugu",
      "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Enugu",
      "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Enugu", "Imo",
      "Imo", "Imo", "Imo", "Enugu", "Enugu", "Imo", "Imo", "Enugu",
      "Enugu", "Imo", "Imo", "Enugu", "Enugu", "Imo", "Enugu", "Enugu",
      "Enugu", "Enugu", "Imo", "Enugu", "Imo", "Enugu", "Imo", "Imo",
      "Imo", "Imo", "Imo", "Enugu", "Imo", "Imo", "Imo", "Imo", "Imo",
      "Abia", "Enugu", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA
    ), lga = c(
      "Enugu East", "Nkanu West",
      "Mbaitoli", "Oru East", "Orlu", "Owerri Municipal", "Okigwe",
      "Obowo", "Owerri North", "Ohaji/Egbema", "Owerri North", "Owerri North",
      "Orlu", "Oru East", "Owerri Municipal", "Nsukka", "aboh mbaise",
      "Isuikwuato", "Aba North", "Ohafia", "Ukwa West", "Obi Ngwa",
      "Osisioma", "Umuahia North", "Aba South", "Obi Ngwa", "Ohafia",
      "Isiala Ngwa North", "Ukwa East", "Umuahia North", "Ugwunagbo",
      "Aba South", "Ukwa West", "Bende", "Bende", "Umuahia North",
      "Bende", "Isuikwuato", "Umuahia South", "Isiala Ngwa South",
      "Ohafia", "Osisioma", "Osisioma", "Umu Nneochi", "Aba South",
      "Ikwuano", "Arochukwu", "Umu Nneochi", "Osisioma", "Aba South",
      "Isuikwuato", "Arochukwu", "Umuahia South", "Isiala Ngwa North",
      "Awgu", "Uzo Uwani", "Udenu", "Enugu North", "Enugu South", "Nkanu West",
      "Enugu South", "Udi", "Nsukka", "Igbo Eze South", "Awgu", "Enugu South",
      "Enugu South", "Igbo Etiti", "Igbo Etiti", "isi uzo", "Enugu North",
      "Oji River", "Enugu East", "Enugu East", "Enugu North", "Oguta",
      "Nwangele", "Njaba", "Isu", "Udi", "Nsukka", "Ezinihitte", "Mbaitoli",
      "Udenu", "Igbo Eze North", "Isiala Mbano", "Owerri North", "Igbo Eze North",
      "Igbo Eze North", "Owerri North", "Awgu", "Udi", "Enugu North",
      "Oji River", "Ideato North", "Nsukka", "aboh mbaise", "Nsukka",
      "Ngor Okpala", "Nwangele", "Ehime Mbano", "Mbaitoli", "Ideato North",
      "Enugu South", "Ngor Okpala", "Ikeduru", "Nkwerre", "Orsu", "Orlu",
      "Obi Ngwa", "Aninri", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA
    ), facility = c(
      "Annunciation Specialist Hospital- Emene",
      "University Of Nigeria Teaching Hospital (UNTH)", "Mbieri General Hospital",
      "Awo Omamma General Hospital", "Imo State University Teaching Hospital",
      "Federal Medical Center - Owerri", "Okigwe General Hospital",
      "Our Lady of Mercy - Obowo", "Holy Rosary Hospital - Emekuku",
      "General Hospital Egbema", "Akwakuma Health Center", "Imo State One Stop Shop (OSS) -  Owerri",
      "im St. Damian Catholic Hospital- Orlu", "Chiwendu Hospital Awo Omama",
      "im Imo Specialist Hospital- Owerri", "en Bishop Shanahan Hospital- Nsukka",
      "Aboh Mbaise General Hospital", "Swiss Foundation Hospital",
      "SEVENTH DAY ADVENTIST HOSPITAL", "Akahaba General Hospital",
      "Owaza Cottage Hospital", "Nigeria Christian Hospital- Nlagu",
      "Ihunanya Specialist Hospital", "Madonna Catholic Hospital",
      "St. Anthony's hospital limited", "Semcon Friends Mission Hospital And Motherless Babies Home",
      "Ohafia General Hospital", "Central Medical Centre", "Azumini Cottage Hospital",
      "Federal Medical Centre Umuahia", "Nwodaku Memory Hospital And Maternity",
      "St. Joseph Catholic Hospital- Ohabia", "Denokem Hospital", "Nkechi Colwill Methodist Hospital",
      "Chijioke Osogho Methodist Memorial Hospital", "Daughters Of Mary Mother Of Mercy Hospital",
      "Royal Cross Methodist Hospital", "Marist Cottage Hospital- Uturu",
      "St. Charles Hospital", "Teresa Orsini Clinic", "King of Kings Specialist Hospital",
      "Government Cottage Hospital", "Living Word Hospital (Osisiamo Ngwa)",
      "St Anthonys Hospital (Amuda)", "Mendel Hospital And Diagnostic Centre",
      "Michael Okpara University Of Agriculture Health Centre", "St AnthonyS Hospital (Arochukwu)",
      "Umu Nneochi General Hospital", "Abia State University Teaching Hospital",
      "New Era Hospital", "General Hospital Isuikwato", "Arochukwu General Hospital",
      "Abia State Specialist Hospital Amachara", "Okpuala Ngwa General Hospital",
      "Mother of Mercy Hospital - Ihe", "Our Lady Health of the Sick Hospital -  Adani",
      "Obollo Affor Health Center", "Royal Hospital -  Iva-ValleyEnugu",
      "The Good Shepherd Hospital - Uwani", "en Agbani District Hospital- Agbani",
      "Uwani Cottage Hospital", "Our Saviour Hospital and Maternity",
      "Nussy Sadiq Memorial Hospital - Nsukka", "Our Lady\"s Clinic",
      "Awgu Maternal and Child Health Clinic", "Balm of Gilead Hospital",
      "Divine Grace Hospital", "Attah Memorial Hospital", "Elechi Medical Clinic - Ukehe",
      "Ikem District Hospital", "Asata Poly Clinic (Sub District Hospital)",
      "Achi Joint Hospital", "Iji Nike Cottage Hospital", "Ntasi-Obi Hospital -  Enugu",
      "Enugu State University Teaching Hospital  (Parklane Specialist Hospital)",
      "Akabo Health Center", "Abba 1 Primary Health Center - Umuopara",
      "Ndukwu Hospital", "Ebenato Ekwe Health Center", "Nsude Health Center",
      "Nsukka Health Center", "Chokoneze Ndutu Primary Health Center",
      "Nworieubi Primary Health Center", "Daughters of Divine Love - Ehalumona",
      "Chima Hospital And Maternity", "im Mbano Joint Hospital", "Naze Health Center",
      "St. Mary Hospital", "Enugu-Ezike District Hospital", "Ihitte-Ogada Health Center",
      "Awgu District Hospital", "Udi District Hospital", "Mother of Christ Specialist Hospital",
      "Oji River Sub District General Hospital", "Immaculate Hospital - Urualla",
      "Nsukka District Hospital", "Holy Rosary Hospital Ogbor Nguru",
      "Faith Foundation Mission Hospital - Nsukka", "Elelem Primary Health Center",
      "St. Mary Joint Hospital - Amaigbo", "Umuezeala Owere Health Center",
      "Ogwa General Hospital", "Osina Community Hospital", "Enugu Eastern Medical Hospital",
      "Ngor Okpala General Hospital", "Iho Basic Health Center", "Owerre Nkworji Health Center",
      "Ebenator Health Center", "im Orlu", "Bishop Afonya Memorial Hospital",
      "Ameke Oduma Health Center", NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
    ), full_name = structure(c(
      "Antoniya Arnetta",
      "Raydel Ramon", "Amia Gisela", "Gilmore Kynzee", "Tandy Xiomy",
      "Rowland Johnathan", "Querida Shalom", "Serene Palmira", "Daryll Tunney",
      "Lakira Travers", "Theresea Dan", "Lupita Janeane", "Devaughn Teretha",
      "Carole Case", "Meital Ann", "Gwynneth Emma", "Riece Terrence",
      "Jun Patrik", "Elzy Niels", "Mio Annalysse", "Rober Charlie",
      "Shamona Morgan", "Shoshanah Magdalene", "Ludwig Teryl", "Rebecca Liesel",
      "Stphanie Eugine", "Dalinda Melton", "Wilburn Markevious", "Leeah Theresea",
      "Gary Oletta", "Arrow Bradon", "Antonella Pascal", "Chantal Eryk",
      "Ave Adara", "Corletta Lindia", "Kyran Casimir", "Dannelle Zeyad",
      "Connor Glennis", "Merrill Djuana", "Brynnan Levy", "Lizzette Zayan",
      "Brock Ahnna", "Lynnox Mandie", "Charito Kim", "Lamika Callan",
      "Margarette Zoran", "Shirlie Saria", "Grecia Sandi", "Haile Tameka",
      "Keigen Darla", "Melody Shadeed", "Nadira Beecher", "Alanna Lovis",
      "Mackenzi Anika", "Joeanne Jody", "Saquita Jamilex", "Greta Magdalene",
      "Cordarius Antroine", "Sonja Maesyn", "Vestal Daevon", "Baley Conye",
      "Kensley Meylin", "Kassity Bette", "Azucena Billie", "Kairo Lenardo",
      "Cristel Carie", "Rommel Nat", "Reginald Joel", "Toronto Ada",
      "Stephani Dennisse", "Domenick Hermena", "Keslee Arsenia", "Delina Stori",
      "Elecia Earlen", "Tyshana Domonique", "Jennifer Trevor", "Annakatherine Masud",
      "Kaylub Stanton", "Laniece Adaneli", "Cloma Star", "Lilyian Daniel",
      "Farrel Averi", "Yates Russell", "Hank Eunice", "Bellatrix Agness",
      "Ambyr Myel", "Elaney Arie", "Elaf Kessa", "Quinton Karaline",
      "Sherrell Uri", "Porfirio Norma", "Lynell Emili", "Claretta Quavis",
      "Evelynn Ayako", "Vannette Corean", "Nora Dianette", "Marve Kaylon",
      "Ivanna Jestin", "Darryll Rachele", "Mariadelcarmen Daily", "Sanjana Jenita",
      "Dezmon Constantine", "Daven Ivana", "Edson Keiaira", "Tyleen Calla",
      "Zilynn Farah", "Carlee Laurel", "Theta Ona", "Susan Russ", "Jelissa Echo",
      "Recardo Pinkney", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA
    ), class = c("glue", "character")),
    email = c(
      "Antoniya.Arnetta@gmail.com", "Raydel.Ramon@gmail.com",
      "Amia.Gisela@gmail.com", "Gilmore.Kynzee@gmail.com", "Tandy.Xiomy@gmail.com",
      "Rowland.Johnathan@gmail.com", "Querida.Shalom@gmail.com",
      "Serene.Palmira@gmail.com", "Daryll.Tunney@gmail.com", "Lakira.Travers@gmail.com",
      "Theresea.Dan@gmail.com", "Lupita.Janeane@gmail.com", "Devaughn.Teretha@gmail.com",
      "Carole.Case@gmail.com", "Meital.Ann@gmail.com", "Gwynneth.Emma@gmail.com",
      "Riece.Terrence@gmail.com", "Jun.Patrik@gmail.com", "Elzy.Niels@gmail.com",
      "Mio.Annalysse@gmail.com", "Rober.Charlie@gmail.com", "Shamona.Morgan@gmail.com",
      "Shoshanah.Magdalene@gmail.com", "Ludwig.Teryl@gmail.com",
      "Rebecca.Liesel@gmail.com", "Stphanie.Eugine@gmail.com",
      "Dalinda.Melton@gmail.com", "Wilburn.Markevious@gmail.com",
      "Leeah.Theresea@gmail.com", "Gary.Oletta@gmail.com", "Arrow.Bradon@gmail.com",
      "Antonella.Pascal@gmail.com", "Chantal.Eryk@gmail.com", "Ave.Adara@gmail.com",
      "Corletta.Lindia@gmail.com", "Kyran.Casimir@gmail.com", "Dannelle.Zeyad@gmail.com",
      "Connor.Glennis@gmail.com", "Merrill.Djuana@gmail.com", "Brynnan.Levy@gmail.com",
      "Lizzette.Zayan@gmail.com", "Brock.Ahnna@gmail.com", "Lynnox.Mandie@gmail.com",
      "Charito.Kim@gmail.com", "Lamika.Callan@gmail.com", "Margarette.Zoran@gmail.com",
      "Shirlie.Saria@gmail.com", "Grecia.Sandi@gmail.com", "Haile.Tameka@gmail.com",
      "Keigen.Darla@gmail.com", "Melody.Shadeed@gmail.com", "Nadira.Beecher@gmail.com",
      "Alanna.Lovis@gmail.com", "Mackenzi.Anika@gmail.com", "Joeanne.Jody@gmail.com",
      "Saquita.Jamilex@gmail.com", "Greta.Magdalene@gmail.com",
      "Cordarius.Antroine@gmail.com", "Sonja.Maesyn@gmail.com",
      "Vestal.Daevon@gmail.com", "Baley.Conye@gmail.com", "Kensley.Meylin@gmail.com",
      "Kassity.Bette@gmail.com", "Azucena.Billie@gmail.com", "Kairo.Lenardo@gmail.com",
      "Cristel.Carie@gmail.com", "Rommel.Nat@gmail.com", "Reginald.Joel@gmail.com",
      "Toronto.Ada@gmail.com", "Stephani.Dennisse@gmail.com", "Domenick.Hermena@gmail.com",
      "Keslee.Arsenia@gmail.com", "Delina.Stori@gmail.com", "Elecia.Earlen@gmail.com",
      "Tyshana.Domonique@gmail.com", "Jennifer.Trevor@gmail.com",
      "Annakatherine.Masud@gmail.com", "Kaylub.Stanton@gmail.com",
      "Laniece.Adaneli@gmail.com", "Cloma.Star@gmail.com", "Lilyian.Daniel@gmail.com",
      "Farrel.Averi@gmail.com", "Yates.Russell@gmail.com", "Hank.Eunice@gmail.com",
      "Bellatrix.Agness@gmail.com", "Ambyr.Myel@gmail.com", "Elaney.Arie@gmail.com",
      "Elaf.Kessa@gmail.com", "Quinton.Karaline@gmail.com", "Sherrell.Uri@gmail.com",
      "Porfirio.Norma@gmail.com", "Lynell.Emili@gmail.com", "Claretta.Quavis@gmail.com",
      "Evelynn.Ayako@gmail.com", "Vannette.Corean@gmail.com", "Nora.Dianette@gmail.com",
      "Marve.Kaylon@gmail.com", "Ivanna.Jestin@gmail.com", "Darryll.Rachele@gmail.com",
      "Mariadelcarmen.Daily@gmail.com", "Sanjana.Jenita@gmail.com",
      "Dezmon.Constantine@gmail.com", "Daven.Ivana@gmail.com",
      "Edson.Keiaira@gmail.com", "Tyleen.Calla@gmail.com", "Zilynn.Farah@gmail.com",
      "Carlee.Laurel@gmail.com", "Theta.Ona@gmail.com", "Susan.Russ@gmail.com",
      "Jelissa.Echo@gmail.com", "Recardo.Pinkney@gmail.com", NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA
    ), phone_number = structure(c(
      "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", "+23486104357", "+23486104357",
      "+23486104357", "+23486104357", NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
    ), class = c(
      "glue",
      "character"
    )), qualification = c(
      "ND", "SSCE", "MSc", "BSc",
      "ND", "BSc", "Diploma", "Others", "Others", "Diploma", "ND",
      "HND", "Others", "Diploma", "Diploma", "Diploma", "HND",
      "MSc", "HND", "Diploma", "ND", "ND", "ND", "SSCE", "HND",
      "Diploma", "BSc", "SSCE", "Diploma", "BSc", "BSc", "ND",
      "BSc", "ND", "ND", "HND", "BSc", "HND", "MSc", "ND", "ND",
      "Diploma", "Diploma", "ND", "Others", "HND", "ND", "Diploma",
      "ND", "ND", "BSc", "HND", "BSc", "SSCE", "Others", "HND",
      "MSc", "HND", "ND", "Diploma", "BSc", "BSc", "ND", "Diploma",
      "Diploma", "Diploma", "Diploma", "Others", "HND", "Others",
      "ND", "BSc", "BSc", "HND", "SSCE", "HND", "SSCE", "HND",
      "Others", "Diploma", "ND", "BSc", "Others", "Diploma", "HND",
      "HND", "SSCE", "BSc", "BSc", "ND", "ND", "Diploma", "BSc",
      "BSc", "SSCE", "BSc", "BSc", "Diploma", "ND", "SSCE", "ND",
      "HND", "BSc", "HND", "HND", "SSCE", "SSCE", "ND", "ND", "BSc",
      "HND", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
      NA, NA, NA, NA, NA, NA, NA
    ), program_area = c(
      "Pharmacy",
      "Monitoring & Evaluation", "Care & Treatment", "Pharmacy",
      "Pharmacy", "Laboratory", "Pharmacy", "Monitoring & Evaluation",
      "Monitoring & Evaluation", "Pharmacy", "Prevention", "Laboratory",
      "Care & Treatment", "Health Informatics", "Care & Treatment",
      "Laboratory", "Pharmacy", "Care & Treatment", "Care & Treatment",
      "Prevention", "Pharmacy", "Care & Treatment", "Monitoring & Evaluation",
      "Prevention", "Care & Treatment", "Monitoring & Evaluation",
      "Prevention", "Care & Treatment", "Health Informatics", "Prevention",
      "Prevention", "Health Informatics", "Monitoring & Evaluation",
      "Prevention", "Care & Treatment", "Laboratory", "Monitoring & Evaluation",
      "Care & Treatment", "Pharmacy", "Monitoring & Evaluation",
      "Monitoring & Evaluation", "Health Informatics", "Prevention",
      "Health Informatics", "Prevention", "Pharmacy", "Laboratory",
      "Prevention", "Health Informatics", "Health Informatics",
      "Health Informatics", "Laboratory", "Pharmacy", "Prevention",
      "Prevention", "Care & Treatment", "Laboratory", "Monitoring & Evaluation",
      "Prevention", "Pharmacy", "Monitoring & Evaluation", "Laboratory",
      "Monitoring & Evaluation", "Monitoring & Evaluation", "Prevention",
      "Care & Treatment", "Laboratory", "Care & Treatment", "Laboratory",
      "Pharmacy", "Laboratory", "Pharmacy", "Care & Treatment",
      "Care & Treatment", "Monitoring & Evaluation", "Laboratory",
      "Care & Treatment", "Pharmacy", "Care & Treatment", "Care & Treatment",
      "Prevention", "Monitoring & Evaluation", "Care & Treatment",
      "Laboratory", "Prevention", "Care & Treatment", "Monitoring & Evaluation",
      "Prevention", "Care & Treatment", "Laboratory", "Laboratory",
      "Health Informatics", "Health Informatics", "Laboratory",
      "Monitoring & Evaluation", "Prevention", "Monitoring & Evaluation",
      "Health Informatics", "Monitoring & Evaluation", "Pharmacy",
      "Monitoring & Evaluation", "Health Informatics", "Health Informatics",
      "Pharmacy", "Prevention", "Monitoring & Evaluation", "Monitoring & Evaluation",
      "Care & Treatment", "Laboratory", "Laboratory", "Prevention",
      "Health Informatics", "Health Informatics", "Laboratory",
      "Care & Treatment", "Monitoring & Evaluation", "Health Informatics",
      "Prevention", "Health Informatics", "Laboratory", "Health Informatics",
      "Prevention", "Care & Treatment", "Pharmacy", "Care & Treatment",
      "Health Informatics", "Pharmacy", "Care & Treatment", "Laboratory",
      "Prevention", "Pharmacy", "Laboratory", "Prevention", "Care & Treatment",
      "Prevention", "Pharmacy", "Care & Treatment", "Care & Treatment",
      "Prevention", "Prevention", "Health Informatics", "Laboratory",
      "Prevention", "Pharmacy", "Care & Treatment", "Laboratory",
      "Care & Treatment", "Health Informatics", "Laboratory", "Prevention",
      "Monitoring & Evaluation", "Prevention", "Prevention", "Prevention",
      "Care & Treatment", "Care & Treatment", "Care & Treatment",
      "Monitoring & Evaluation", "Laboratory", "Monitoring & Evaluation",
      "Pharmacy"
    ), indicators = c(
      "VL coverage", "IIT rate, prop. missed appointments tracked",
      "IIT rate", "VL coverage", "IIT rate", "VL suppression rate",
      "IIT rate", "IIT rate", "VL suppression rate", "VL coverage, VL suppression rate",
      "number of new cases", "IIT rate", "VL coverage, VL suppression rate",
      "IIT rate", "VL coverage", "VL suppression rate", "VL coverage, VL suppression rate",
      "IIT rate, prop. missed appointments tracked", "VL coverage, VL suppression rate",
      "VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage, VL suppression rate", "number of new cases",
      "VL coverage", "VL suppression rate", "IIT rate", "IIT rate",
      "VL coverage, VL suppression rate", "VL coverage", "VL coverage, VL suppression rate",
      "number of new cases", "number of new cases", "IIT rate",
      "IIT rate, prop. missed appointments tracked", "VL coverage",
      "IIT rate", "IIT rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage, VL suppression rate", "VL suppression rate",
      "VL suppression rate", "number of new cases", "number of new cases",
      "number of new cases", "IIT rate", "IIT rate", "number of new cases",
      "VL coverage", "IIT rate", "VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "VL suppression rate", "number of new cases", "number of new cases",
      "IIT rate", "VL suppression rate", "IIT rate", "VL coverage, VL suppression rate",
      "IIT rate, prop. missed appointments tracked", "number of new cases",
      "number of new cases", "number of new cases", "VL coverage, VL suppression rate",
      "VL coverage, VL suppression rate", "VL suppression rate",
      "VL coverage, VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "IIT rate", "IIT rate", "VL coverage, VL suppression rate",
      "VL coverage, VL suppression rate", "number of new cases",
      "VL coverage", "VL coverage", "VL suppression rate", "IIT rate",
      "number of new cases", "VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage", "VL coverage, VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "VL suppression rate", "VL suppression rate", "number of new cases",
      "VL suppression rate", "IIT rate", "VL coverage", "IIT rate",
      "VL coverage, VL suppression rate", "VL coverage, VL suppression rate",
      "number of new cases", "IIT rate", "VL coverage, VL suppression rate",
      "VL coverage, VL suppression rate", "VL coverage", "VL coverage, VL suppression rate",
      "VL coverage, VL suppression rate", "VL coverage, VL suppression rate",
      "number of new cases", "IIT rate, prop. missed appointments tracked",
      "IIT rate, prop. missed appointments tracked", "IIT rate",
      "VL suppression rate", "IIT rate", "VL coverage", "IIT rate, prop. missed appointments tracked",
      "number of new cases", "VL coverage, VL suppression rate",
      "VL suppression rate", "IIT rate", "number of new cases",
      "VL suppression rate", "number of new cases", "number of new cases",
      "VL suppression rate", "VL coverage", "VL coverage", "VL suppression rate",
      "IIT rate, prop. missed appointments tracked", "IIT rate, prop. missed appointments tracked",
      "VL coverage, VL suppression rate", "VL coverage, VL suppression rate",
      "IIT rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage, VL suppression rate", "VL suppression rate",
      "VL suppression rate", "VL coverage", "VL suppression rate",
      "number of new cases", "number of new cases", "IIT rate",
      "VL coverage, VL suppression rate", "VL suppression rate",
      "IIT rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage", "IIT rate", "VL coverage", "IIT rate, prop. missed appointments tracked",
      "VL coverage", "VL coverage", "IIT rate, prop. missed appointments tracked",
      "IIT rate, prop. missed appointments tracked", "VL suppression rate",
      "IIT rate, prop. missed appointments tracked", "VL coverage, VL suppression rate",
      "VL suppression rate", "IIT rate, prop. missed appointments tracked",
      "VL coverage", "number of new cases", "VL coverage, VL suppression rate",
      "VL suppression rate", "VL coverage", "VL coverage", "VL coverage, VL suppression rate",
      "VL coverage, VL suppression rate", "IIT rate", "VL coverage",
      "VL coverage, VL suppression rate"
    ), courses_taken = c(
      "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Introduction to HIV/AIDS Program Management", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Ethics & confidentiality",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "Ethics & confidentiality",
      "HIV Prevention, Care and Treatment", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Ethics & confidentiality",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population"
    ), planned_courses = c(
      "HIV Prevention, Care and Treatment",
      "HIV Prevention, Care and Treatment", "Ethics & confidentiality",
      "HIV Prevention, Care and Treatment", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Introduction to HIV/AIDS Program Management", "Introduction to HIV/AIDS Program Management",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV/AIDS: Strategy, Planning & Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "Ethics & confidentiality",
      "HIV Prevention, Care and Treatment", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV/AIDS: Strategy, Planning & Management",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Introduction to HIV/AIDS Program Management",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality"
    ), urgent_courses = c(
      "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Ethics & confidentiality", "HIV/AIDS: Strategy, Planning & Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Ethics & confidentiality", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Introduction to HIV/AIDS Program Management", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV Prevention, Care and Treatment", "HIV Prevention, Care and Treatment",
      "Introduction to HIV/AIDS Program Management", "HIV/AIDS: Strategy, Planning & Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "HIV Prevention, Care and Treatment",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV/AIDS: Strategy, Planning & Management",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "HIV Prevention, Care and Treatment",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Ethics & confidentiality", "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV Prevention, Care and Treatment", "HIV/AIDS: Strategy, Planning & Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Developing and Managing HIV Prevention Programs for At-Risk Population",
      "HIV/AIDS: Strategy, Planning & Management", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "Introduction to HIV/AIDS Program Management", "Ethics & confidentiality",
      "Ethics & confidentiality", "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation",
      "HIV/AIDS: Strategy, Planning & Management", "Ethics & confidentiality",
      "HIV Prevention, Care and Treatment", "Introduction to HIV/AIDS Program Management",
      "Fundamentals of HIV, Bases of HIV Monitoring & Evaluation"
    ), iit_rate = c(
      0.025, 0.034, 0.047, 0.018, 0.007, 0.036,
      0.03, 0.041, 0.021, 0.028, 0.016, 0.012, 0.004, 0.02, 0.025,
      0.023, 0.047, 0.004, 0.004, 0.027, 0.039, 0.039, 0.048, 0.044,
      0.024, 0.048, 0.01, 0.01, 0.02, 0.038, 0.031, 0.041, 0.034,
      0.035, 0.025, 0.012, 0.022, 0.013, 0.004, 0.031, 0.044, 0.04,
      0.034, 0.005, 0.01, 0.027, 0.043, 0.035, 0.038, 0.014, 0.028,
      0.049, 0.05, 0.032, 0.05, 0.031, 0.05, 0.024, 0.027, 0.024,
      0.002, 0.039, 0.045, 0.022, 0.016, 0.035, 0.016, 0.017, 0.022,
      0.042, 0.042, 0.008, 0.033, 0.043, 0.004, 0.012, 0.024, 0.042,
      0.002, 0.024, 0.043, 0.023, 0.003, 0.043, 0.04, 0.036, 0.003,
      0.026, 0.041, 0.021, 0.038, 0.012, 0.017, 0.039, 0.009, 0.01,
      0.018, 0.031, 0.02, 0.046, 0.029, 0.041, 0.016, 0.007, 0.03,
      0.022, 0.008, 0.021, 0.003, 0.04, 0.022, 0.049, 0.006, 0.023,
      0.022, 0.014, 0.028, 0.022, 0.019, 0.044, 0.036, 0.045, 0.04,
      0.049, 0.05, 0.039, 0.002, 0.003, 0.03, 0.038, 0.016, 0.011,
      0.04, 0.001, 0.004, 0.027, 0.049, 0.041, 0.022, 0.022, 0.013,
      0.043, 0.009, 0.044, 0.035, 0.003, 0.015, 0.041, 0.001, 0.015,
      0.01, 0.021, 0.011, 0.029, 0.008, 0.017, 0.04, 0.016, 0.003,
      0.017, 0.04
    ), vl_coverage = c(
      0.34, 0.36, 0.63, 0.61, 0.31,
      0.43, 0.8, 0.63, 0.4, 0.45, 0.54, 0.46, 0.7, 0.56, 0.71,
      0.78, 0.87, 0.86, 0.53, 0.72, 0.4, 0.33, 0.9, 0.74, 0.77,
      0.5, 0.47, 0.53, 0.66, 0.91, 0.72, 0.64, 0.59, 0.79, 0.76,
      0.95, 0.88, 0.73, 0.55, 0.72, 0.79, 0.38, 0.87, 0.43, 0.9,
      0.8, 0.83, 0.68, 0.73, 0.51, 0.7, 0.46, 0.79, 0.63, 0.73,
      0.74, 0.33, 0.74, 0.31, 0.82, 0.8, 0.35, 0.4, 0.82, 0.32,
      0.38, 0.37, 0.33, 0.66, 0.86, 0.71, 0.45, 0.32, 0.58, 0.49,
      0.74, 0.57, 0.37, 0.93, 0.79, 0.61, 0.89, 0.82, 0.48, 0.34,
      0.42, 0.82, 0.67, 0.48, 0.55, 0.94, 0.72, 0.36, 0.75, 0.7,
      0.72, 0.52, 0.76, 0.8, 0.63, 0.47, 0.63, 0.37, 0.55, 0.9,
      0.54, 0.93, 0.67, 0.59, 0.8, 0.82, 0.46, 0.39, 0.72, 0.57,
      0.36, 0.52, 0.52, 0.53, 0.78, 0.87, 0.37, 0.31, 0.74, 0.89,
      0.64, 0.86, 0.89, 0.53, 0.71, 0.35, 0.71, 0.61, 0.74, 0.48,
      0.86, 0.36, 0.31, 0.46, 0.7, 0.51, 0.5, 0.43, 0.93, 0.47,
      0.93, 0.89, 0.88, 0.66, 0.91, 0.66, 0.8, 0.59, 0.84, 0.6,
      0.61, 0.72, 0.91, 0.33, 0.6, 0.79
    ), vls_rate = c(
      0.82, 0.95,
      0.93, 0.81, 0.86, 0.86, 0.81, 0.91, 0.85, 0.86, 0.85, 0.93,
      0.84, 0.95, 0.86, 0.96, 0.92, 0.84, 0.93, 0.97, 0.85, 0.88,
      0.9, 0.92, 0.94, 0.83, 0.86, 0.84, 0.82, 0.95, 0.87, 0.92,
      0.85, 0.8, 0.89, 0.94, 0.81, 0.85, 0.87, 0.94, 0.93, 0.85,
      0.82, 0.92, 0.88, 0.84, 0.96, 0.86, 0.92, 0.82, 0.91, 0.82,
      0.92, 0.97, 0.9, 0.8, 0.95, 0.86, 0.8, 0.86, 0.96, 0.82,
      0.88, 0.94, 0.93, 0.91, 0.91, 0.9, 0.85, 0.81, 0.9, 0.92,
      0.81, 0.86, 0.88, 0.83, 0.92, 0.91, 0.97, 0.93, 0.87, 0.97,
      0.84, 0.85, 0.92, 0.92, 0.89, 0.86, 0.82, 0.95, 0.8, 0.95,
      0.97, 0.91, 0.96, 0.94, 0.87, 0.84, 0.93, 0.88, 0.84, 0.89,
      0.92, 0.86, 0.96, 0.86, 0.81, 0.83, 0.95, 0.82, 0.8, 0.91,
      0.93, 0.88, 0.95, 0.9, 0.8, 0.93, 0.89, 0.91, 0.82, 0.89,
      0.85, 0.94, 0.86, 0.84, 0.88, 0.9, 0.83, 0.9, 0.88, 0.92,
      0.89, 0.97, 0.83, 0.87, 0.97, 0.83, 0.91, 0.91, 0.81, 0.9,
      0.8, 0.8, 0.93, 0.91, 0.87, 0.82, 0.94, 0.88, 0.87, 0.89,
      0.97, 0.88, 0.87, 0.95, 0.96, 0.92, 0.82, 0.96, 0.85
    ), reg_optimization_rate = c(
      0.81,
      0.8, 0.95, 0.96, 0.8, 0.88, 0.81, 0.91, 0.95, 0.85, 0.9,
      0.91, 0.83, 0.94, 0.87, 0.88, 0.97, 0.96, 0.8, 0.84, 0.92,
      0.84, 0.84, 0.96, 0.87, 0.87, 0.88, 0.88, 0.96, 0.94, 0.96,
      0.93, 0.88, 0.94, 0.86, 0.87, 0.9, 0.83, 0.94, 0.8, 0.9,
      0.95, 0.87, 0.86, 0.92, 0.87, 0.89, 0.93, 0.85, 0.88, 0.87,
      0.8, 0.9, 0.82, 0.84, 0.88, 0.89, 0.87, 0.95, 0.92, 0.86,
      0.85, 0.95, 0.83, 0.82, 0.8, 0.81, 0.96, 0.83, 0.94, 0.81,
      0.91, 0.92, 0.96, 0.96, 0.91, 0.94, 0.91, 0.86, 0.88, 0.95,
      0.91, 0.93, 0.85, 0.9, 0.83, 0.8, 0.84, 0.94, 0.81, 0.91,
      0.83, 0.81, 0.84, 0.93, 0.87, 0.8, 0.94, 0.85, 0.92, 0.87,
      0.84, 0.97, 0.88, 0.82, 0.81, 0.95, 0.94, 0.96, 0.8, 0.89,
      0.8, 0.9, 0.81, 0.95, 0.94, 0.89, 0.9, 0.83, 0.88, 0.84,
      0.86, 0.86, 0.92, 0.93, 0.93, 0.84, 0.89, 0.88, 0.92, 0.85,
      0.85, 0.89, 0.88, 0.89, 0.93, 0.83, 0.96, 0.86, 0.89, 0.93,
      0.97, 0.91, 0.94, 0.9, 0.91, 0.9, 0.86, 0.81, 0.85, 0.85,
      0.82, 0.94, 0.92, 0.81, 0.91, 0.92, 0.92, 0.82, 0.81, 0.8
    )
  ), row.names = c(NA, 161L), class = "data.frame")
}
